---
input_tables:
    - dim_business_unit
    - dim_card
    - dim_merchant
    - dim_merchant_all
    - dim_transaction_type
    - dim_sales_agent
    - dim_sales_agent_group
    - dim_sales_office
    - dim_sales_rep
    - dim_sales_rep_office
    - dim_contact_all
other_params:
    row_count_limit: 50
    gx_data_src_name: gx_datasource_snowflake
    cols_to_exclude:
